In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [32]:
C = np.array([[1,5],
              [3,2]])

In [33]:
def softmax(matrix):

    # Subtract the max for numerical stability
    exp_matrix = np.exp(matrix - np.max(matrix, axis=0, keepdims=True))
    # Apply softmax
    softmax_matrix = exp_matrix / np.sum(exp_matrix, axis=0, keepdims=True)
    return softmax_matrix

softmax_matrix = softmax(C)
print(softmax_matrix)


[[0.11920292 0.95257413]
 [0.88079708 0.04742587]]


In [34]:
def normalize_row(row):
    row_sum = np.sum(row)
    if row_sum > 1:
        return row / row_sum
    return row

def normalize_matrix_rows(matrix):
    # Apply normalization to each row
    normalized_mat = np.array([normalize_row(row) for row in matrix])
    return normalized_mat


# Example usage
matrix = C.copy()

normalized_matrix = normalize_matrix_rows(matrix)
print(normalized_matrix)



[[0.16666667 0.83333333]
 [0.6        0.4       ]]


In [35]:
def get_row_sums(matrix):
  return np.sum(matrix, axis=1)
def get_col_sums(matrix):
  return np.sum(matrix, axis=0)

In [36]:
get_row_sums(matrix = C.copy()),get_col_sums(matrix = C.copy())

(array([6, 5]), array([4, 7]))

In [37]:
def g(matrix):
  ret_mat = normalize_matrix_rows(softmax(matrix)).copy()
  r = get_row_sums(ret_mat)
  c = get_col_sums(ret_mat)
  r_tild = np.ones(len(ret_mat)) - r
  c_tild = np.ones(len(ret_mat)) - c
  # Actual computation
  ret_mat = ret_mat + (1/np.sum(c_tild))*np.outer(r_tild,c_tild)
  return ret_mat

output_mat = g(C.copy())

In [38]:
get_row_sums(output_mat), get_col_sums(output_mat)

(array([1., 1.]), array([1., 1.]))